#!/bin/bash
echo $(( $(echo "$WATER" | tr 'water' '01234' | awk '{d=0; for(i=1;i<=length;i++){d=d*5+substr($0,i,1)}; print d}') + $(echo "$STIR" | tr 'stir' '0123' | awk '{d=0; for(i=1;i<=length;i++){d=d*4+substr($0,i,1)}; print d}') )) | awk '{s=$1; r=""; if(s==0){print 0; exit}; while(s>0){r=(s%8) r; s=int(s/8)}; print r}' | tr '01234567' 'bestchol'
