#!/usr/bin/env bash
#creatign a file containing its pid 
sudo bash -c "echo$$ >/var/run/myscript.pid" 
trap 'echo" Y U no love me?!"' SIGNIT
trap 'echo "I hate the kill command"; sudo rm -f /var/run/myscript.pid; exit' SIGTERM 
trap 'sudo rm -f /var/run/myscript.pid; exit'
SIGQUIT

while :
do 
   echo "TO infinity and beyond"
    sleep 2
done 
