#!/usr/bin/env bash
# this script kills the process 
for pid in /proc/[0-9]*; do 
    if [ -r "$pid/cmdline" ]; then 
       cmdline=$(tr '\0' ' ' < "$pid/cmdline")
       if echo "$cmdline" | grep -q "4-to_infinity_and_beyond"; then 
          kill "$(basename "$pid")"
       fi 
    fi
done 
